### ISSUE TITLE
Repetitive name part in path

### ISSUE THREAD

**Issue by amerlyq** [kana/vim-altr#12]
I can't figure out how to setup toggle rules in such case:
```
project/src/submodule1/inc/main.h
project/src/submodule1/src/main.c
```
As you can see, ```src``` part repeated for last file.
Rule ```call altr#define('src/%.c', 'inc/%.h')``` works only for ```h -> c```.
But when you try ```c -> h``` it will stuck with first general ```src``` and tries to find file ```project/src/main.h```.

It seems like must be:  ```% == [^\\/]```, or you can add some another separator of that format?
Or there is more convenient way?

**Comment by kana** [comment]
Try `call altr#define('%/src/%.c', '%/inc/%.h')`.

**Comment by amerlyq** [comment]
Ooh, it works! Now it's obvious, however it wasn't such before you answer:)
Maybe, you add this tip to docs? Nevertheless, issue solved.
