### ISSUE TITLE
Allow to set buffers as listed

### ISSUE THREAD

**Issue by stsewd** [kana/vim-altr#14]
Currently if I change between buffers, those are marked as `unlisted`, would be nice to have this configurable :)

Awesome plugin by the way!

**Comment by stsewd** [comment]
mmm, looks like when I do `:bdelete` the buffer is `unload`, and then when I switched back it remains as `unload`, because the `[N]buffer` command is used. So, why not always use the `edit` excommand?
https://github.com/kana/vim-altr/blob/05d4150d8867f4dfb22bc38f832317ae24b8c2d2/autoload/altr.vim#L443

**Comment by kana** [comment]
Because the last cursor position is not restored with `:edit`.  It also has various side effects. So that I chose to use `:buffer` as much as possible for this plugin.

**Comment by kana** [comment]
Try

```
edit a
put =range(10)
5
write
enew
buffer a
enew
edit a
```

**Comment by stsewd** [comment]
@kana I have to test this without plugins to see it, I'm not sure what plugins does solve this for me. Also I was able to note that the cursor position is changed, now I'm using this to fix that https://stackoverflow.com/questions/4251533/vim-keep-window-position-when-switching-buffers#4255960

Well, now I understand why you use `:buffer` to switch to a previous open buffer. But I would like to see the buffer as listed, any suggestion? Maybe adding a `user autocommand` after switching the buffer? or my other suggestion about a configuration to allow to use always `:edit`?

**Comment by kana** [comment]
The cause of the problem is use of `:bdelete`.  Why do you use `:bdelete`?  The command is sometimes useful if you develop Vim plugins, but it is not practical for interactive use unless you are really aware what it does.  So that I believe the best solution is to not use `:bdelete`.

**Comment by stsewd** [comment]
Then should I use `:bwipeout`? I actually use https://github.com/mhinz/vim-sayonara for closing buffers/windows and everything else. I'm really not sure why isn't practical.

**Comment by kana** [comment]
>  I actually use https://github.com/mhinz/vim-sayonara
It should be mentioned at first to save time…

Just use `:close`.  This covers most cases of what `:Sayonara` does.  Then `:Sayonara` is only useful for the following situation: "There is only one tab page and one window, I finished editing this file, I don't want to see it anymore in this session, but I have more files to edit which I've opened in this session, and I want to quickly reopen one of those files".  In this case `:bdelete` is the proper command.

**Comment by stsewd** [comment]
> "There is only one tab page and one window, I finished editing this file, I don't want to see it anymore in this session, but I have more files to edit which I've opened in this session, and I want to quickly reopen one of those files".

Currently that is my daily workflow. I just work on one tab with 2 splits max, and several buffers, I use `:bdelete` to not see it, but is very probably that I will need to edit it later.

**Comment by kana** [comment]
Okay, I'll tweak the `:buffer`-or-`:edit` condition to work also for your workflow.

**Comment by stsewd** [comment]
@kana really appreciated, thanks for taking that time and quickly response! :100:

**Comment by kana** [comment]
@stsewd I've tweaked the condition. Please try https://github.com/kana/vim-altr/pull/16

**Comment by stsewd** [comment]
@kana yeah, that works as expected, pretty cool solution.
