### ISSUE TITLE
Mapping doesn't work

### ISSUE THREAD

**Issue by igorsol** [kana/vim-altr#19]
Trying to use use altr to switch between c++ .cpp/.h.
The switch works ok when i enter the command directly:
```
   :call altr#forward()
```
But if I try to use keyboard mapping in my .vimrc:
```
nmap <F2> <Plug>(altr-forward)
```
then nothing happens when i press mapped key. I tried to map various keys to the `<Plug>(altr-forward)` but nothing works so my conclusion is the the problem is in `<Plug>(altr-forward)` itself.

Vim version is 
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct 28 2019 12:49:47)
Included patches: 1-2231
```

**Comment by kana** [comment]
That's strange. The key mapping should work, and I couldn't reproduce the problem with the same version of Vim and the following minimal configuration:

```sh
vim -u NONE -i NONE -N -n -c 'set rtp=~/tmp/vim-altr | runtime! plugin/**.vim | nmap <F2> <Plug>(altr-forward)'
```

(where `~/tmp/vim-altr` contains the latest version of this plugin.)

Is the problem still reproducible with the above configuration?

**Comment by igorsol** [comment]
Thank you for the example. Yes, it works with minimal configuration. So I will try to find out what other part of my config prevents `<Plug>(altr-forward)` from working.

**Comment by igorsol** [comment]
It seems there was some incompatibility with vim sessions. I created vim session with `:mks` command before adding altr mapping to my .vimrc, then I added mappings and restarted vim with `-S Session.vim` parameter. The new mapping didn't work.

I tried to start vim without `-S Session.vim` parameter and now mappings are working.

Finally I removed old Session.vim file and created new one. Now my mappings are working even when I start vim with `-S Session.vim`.

Conclusion: it seems a good idea to kill and recreate all Session.vim files after any changes made to .vimrc.

@kana thank you, you can close this issue.
